### ISSUE TITLE
Suggestions?

### ISSUE THREAD

**Issue by jrean** [daylerees/kurenai#14]
Hi @daylerees,
It is very funny I was working on something similar and I just discovered your repository.

May I bring some suggestions?

When you parse the document for metadata, why don't you use `use Symfony\Component\Yaml\Yaml;
` and then something like `Yaml::parse($metadata);`. With that we will end with a similar `key` => `value' (multidimensional) array and you bring the power of Yaml inside your package which means we can put even more structured metadata.

My code looks like the following.

```
---
title: foo
slug: bar
tags: [foo, bar, baz]
related:
    - foo: bar
      baz: doo
---
@
# My markdown content
@
```

Then I extract the content with:

```
    /**
     * Extract content inside delimiters.
     *
     * @param string $start
     * @param string $end
     * @return string Extracted content.
     *
     * @source
     * http://www.bitrepository.com/extract-content-between-two-delimiters-with-php.html
     */
    protected function extract_unit($string, $start, $end)
    {
        $pos        = stripos($string, $start);
        $str        = substr($string, $pos);
        $str_two    = substr($str, strlen($start));
        $second_pos = stripos($str_two, $end);
        $str_three  = substr($str_two, 0, $second_pos);

        return trim($str_three);
    }
```

But I admit I feel stupid because in your code you don't even need to use delimiter for the markdown content... I will dig in your code to see how you do the magic.

Then, once I have extracted the content between `---` I simply parse it with: `return Yaml::parse($this->extract_unit($content, '---', '---'));` and voila.

What do you think about it and the use of Yaml?

**Comment by crynobone** [comment]
Not sure if Dayle Rees still wanna maintain this project, but I already fork the project and add symfony/yaml support at <https://github.com/laravie/kurenai>
